environment:
  QTDIR: C:\Qt\5.14.1\mingw73_64
  MINGW: C:\Qt\Tools\mingw730_64
  make_cmd: mingw32-make
  
install:
  # Set PATH variable to contain qmake and mingw32-make
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin

  # Download package for QHotkey from QtPlay fork
  - sh ./tools/download_package.sh "QtPlay/QHotkey" "QHotkey" "1.1.0"
  
  # Download package for googletest release 1.10.0
  - sh ./tools/download_package.sh "google/googletest" "googletest" "release-1.10.0"
  
  # Download package for FFmpeg release 4.2.2 with lib build
  - appveyor DownloadFile https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-4.2.2-win64-dev.zip
  - 7z x ffmpeg-4.2.2-win64-dev.zip -oexternal -y
  - mv external/ffmpeg-4.2.2-win64-dev external/FFmpeg
  
build_script:
  # Build SimpleScript
  - sh ./tools/build_project.sh

test_script:
  # Create folder for build
  - mkdir tests/build-Release

  # Download FFmpeg dlls to be able to run executable
  - appveyor DownloadFile https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-4.2.2-win64-shared.zip
  - 7z x ffmpeg-4.2.2-win64-shared.zip -o. -y
  - mv tests/build-Release/ffmpeg-4.2.2-win64-shared/bin/*.dll tests/build-Release
  
  # Clean up
  - rm -rf tests/build-Release/ffmpeg-4.2.2-win64-shared
  
  # Run testcases
  sh ./tools/run_tests.sh'
