environment:
  QTDIR: C:\Qt\5.14\mingw73_64
  MINGW: C:\Qt\Tools\mingw730_64
  make_cmd: mingw32-make
  
install:
  # Set PATH variable to contain qmake and mingw32-make
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin

  # Download package for QHotkey from QtPlay fork
  - sh ./ci-tools/download_github_release.sh "QtPlay" "QHotkey" "1.1.0"
  
  # Download package for googletest release 1.10.0
  - sh ./ci-tools/download_github_release.sh "google" "googletest" "release-1.10.0"
  
  # Download package for FFmpeg release 4.2.2 with lib build
  - appveyor DownloadFile https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-4.2.2-win64-dev.zip
  - 7z x ffmpeg-4.2.2-win64-dev.zip -oexternal -y
  - mv external/ffmpeg-4.2.2-win64-dev external/FFmpeg
  
build_script:
  # Build SimpleScript
  - sh ./ci-tools/build_project.sh

test_script:
  - cd tests

  # Download FFmpeg dlls to be able to run executable
  - appveyor DownloadFile https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-4.2.2-win64-shared.zip
  - 7z x ffmpeg-4.2.2-win64-shared.zip -o. -y
  
  # Move dlls to build-Release and clean up
  - mkdir build-Release
  - mv ffmpeg-4.2.2-win64-shared/bin/*.dll build-Release
  - rm -rf ffmpeg-4.2.2-win64-shared
  - cd ..
  
  # Run testcases
  - sh ./ci-tools/run_tests.sh
