language: cpp
os: osx
compiler: clang

before_install:
  - brew update > /dev/null
  - brew unlink python@2

install:
  - brew install qt5
  - brew install ffmpeg

  # Download QHotkey relase 1.1.0 from QtPlay fork
  - ./tools/download_package.sh "QHotkey" "QtPlay/QHotkey" "1.1.0" "QHotkey" "QHotkey"

  # Download googletest release-1.10.0
  - ./tools/download_package.sh "googletest" "google/googletest" "release-1.10.0" "googletest-release-1.10.0" "googletest/src"

script:
  -    QTDIR="/usr/local/opt/qt5"
    && PATH="$QTDIR/bin:$PATH"
  - mkdir build-Release
  - qmake SimpleScript.pro -o build-Release
  - cd build-Release
  - make
