language: cpp
os: osx
compiler: clang

before_install:
  - brew update > /dev/null
  - brew unlink python@2

install:
  - brew install qt5
  - brew install ffmpeg
  
  - git clone https://github.com/QtPlay/QHotkey
  - cd QHotkey
  - git reset --hard e1f90f15bcf472e112061ad36ecb213a8637c975
  - cd ..
  - mkdir external
  - mv QHotkey/QHotkey external
  - rm -rf QHotkey

script:
  -    QTDIR="/usr/local/opt/qt5"
    && PATH="$QTDIR/bin:$PATH"
  - mkdir build-Release
  - qmake SimpleScript.pro -o build-Release
  - cd build-Release
  - make
