language: cpp
os: osx

install:
  - brew update > /dev/null
  - brew install qt5
  - brew install ffmpeg

script:
  -    QTDIR="/usr/local/opt/qt5"
    && PATH="$QTDIR/bin:$PATH"
    && LDFLAGS=-L$QTDIR/lib
    && CPPFLAGS=-I$QTDIR/include
  - qmake SimpleScript.pro
  - make
