language: cpp
os: osx
compiler: clang

env:
  global:
    - QTDIR=/usr/local/opt/qt5
    - make_cmd=make

before_install:
  - brew update > /dev/null
  - brew unlink python@2

  # Add qmake to path
  - PATH="$QTDIR/bin:$PATH"

install:
  # Download QHotkey release 1.1.0 from QtPlay fork
  - sh ./ci-tools/download_package.sh "QtPlay/QHotkey" "QHotkey" "1.1.0"

  # Download googletest release-1.10.0
  - sh ./ci-tools/download_package.sh "google/googletest" "googletest" "release-1.10.0"
  
  - brew install ffmpeg

jobs:
  include:
    - name: "MacOS Build"
      script: sh ./ci-tools/build_project.sh
    - name: "Unit Tests"
      script: sh ./ci-tools/run_tests.sh
