language: cpp
os: osx

install:
  - brew update
  - brew upgrade qt

script:
  -    QTDIR="/usr/local/opt/qt5"
    && PATH="$QTDIR/bin:$PATH"
    && LDFLAGS=-L$QTDIR/lib
    && CPPFLAGS=-I$QTDIR/include
  - qmake SimpleScript.pro
  - make
