language: cpp
os: osx

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
       brew update > /dev/null
    && brew install qt5
    && brew unlink python@2
    && brew install ffmpeg
    ; 
    fi

script:
  - qmake SimpleScript.pro
  - make
