language: cpp
os: osx
compiler: clang

before_install:
  - brew update > /dev/null
  - brew unlink python@2

  -    QTDIR="/usr/local/opt/qt5"
    && PATH="$QTDIR/bin:$PATH"

install:
  - brew install qt5
  - brew install ffmpeg

  # Download QHotkey release 1.1.0 from QtPlay fork
  - sh ./tools/download_package.sh "QHotkey" "QtPlay/QHotkey" "1.1.0" "QHotkey-1.1.0"

  # Download googletest release-1.10.0
  - sh ./tools/download_package.sh "googletest" "google/googletest" "release-1.10.0" "googletest-release-1.10.0"

jobs:
  include:
    - name: "Unit Tests"
    - script:
      cd ~
      mkdir build-Release
      qmake tests.pro -o build-Release
      cd build-Release
      make
      ./tests -v
    - name: "Project Build"
    - script:
      cd ~
      mkdir build-Release
      qmake SimpleScript.pro -o build-Release
      cd build-Release
      make
