language: cpp
os: osx
compiler: clang

before_install:
  - brew update > /dev/null
  - brew unlink python@2

install:
  - brew install qt5
  - brew install ffmpeg
  
  # Download QHotkey from QtPlay fork
  - git clone https://github.com/QtPlay/QHotkey
  - cd QHotkey
  - git reset --hard e1f90f15bcf472e112061ad36ecb213a8637c975
  - cd ..
  - mkdir external
  - mv QHotkey/QHotkey external
  - rm -rf QHotkey

  # Download googletest release-1.10.0 from archives
  -    gtest_repo="google/googletest"
    && release="release-1.10.0"
    && download_url="https://codeload.github.com/$gtest_repo/tar.gz/$release"
    && target_dir="googletest-$release"
    && target_file="$release.tar.gz"
  - curl -o $target_file $download_url
  - tar -xvf $target_file
  -    mkdir external/googletest
    && shopt -s dotglob nullglob
    && mv $target_dir/googletest/src/* external/googletest
    && rm -rf $target_dir

script:
  -    QTDIR="/usr/local/opt/qt5"
    && PATH="$QTDIR/bin:$PATH"
  - mkdir build-Release
  - qmake SimpleScript.pro -o build-Release
  - cd build-Release
  - make
