before_install:
  - set QTDIR=C:\Qt\5.14.1\mingw73_64
  - set MINGW=C:\Qt\Tools\mingw730_64
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin
install:
    # Download package for QHotkey from QtPlay fork
  - sh ./tools/download_package.sh "QHotkey" "QtPlay/QHotkey" "1.1.0" "QHotkey-1.1.0"
build_script:
  - mkdir build-Release
  - qmake SimpleScript.pro -o build-Release
